@server = http://localhost:4004

GET {{server}}/app/Favourites
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==

###
GET {{server}}/app/Favourites?$filter=itemType_id eq 3
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==

###
POST {{server}}/app/Favourites
Content-Type: application/json
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==

{
    "itemID": 11998911,
    "itemType_id": 6
}

### ADD FAVOURITE
POST {{server}}/app/Favourites
Content-Type: application/json
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==

{
    "itemID": 117611,
    "itemType_id": 1
}

### CREATE CUSOM PLAYLIST ID 0dde954b-d95e-481f-b1d7-a86285b3d6c1
POST {{server}}/app/CustomPlaylists
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==
Content-Type: application/json

{
    "title": "My Playlist 1"
}


### ADD TRACK TO CUSTOM PLAYLIST ID 0dde954b-d95e-481f-b1d7-a86285b3d6c1
POST {{server}}/app/CustomPlaylists(0dde954b-d95e-481f-b1d7-a86285b3d6c1)/tracks
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==
Content-Type: application/json

{
    "trackID" : 3435464
    
}

### UPDATE PERSONALISATION
PATCH  {{server}}/app/Personalizations('.ermolich@gmail.com')
Content-Type: application/json
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==

{
    "iconID": 3
}

###
POST {{server}}/app/Personalizations
Content-Type: application/json
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==

{}

###
GET {{server}}/app/Personalizations
Authorization: Basic ZGFzaGEuZXJtb2xpY2hAZ21haWwuY29tOg==